services:
    # Register nyholm/psr7 services for autowiring with PSR-17 (HTTP factories)
    Psr\Http\Message\RequestFactoryInterface: '@guzzle.psr7.psr17_factory'
    Psr\Http\Message\ResponseFactoryInterface: '@guzzle.psr7.psr17_factory'
    Psr\Http\Message\ServerRequestFactoryInterface: '@guzzle.psr7.psr17_factory'
    Psr\Http\Message\StreamFactoryInterface: '@guzzle.psr7.psr17_factory'
    Psr\Http\Message\UploadedFileFactoryInterface: '@guzzle.psr7.psr17_factory'
    Psr\Http\Message\UriFactoryInterface: '@guzzle.psr7.psr17_factory'

    # Register nyholm/psr7 services for autowiring with HTTPlug factories
    Http\Message\MessageFactory: '@guzzle.psr7.httplug_factory'
    Http\Message\RequestFactory: '@guzzle.psr7.httplug_factory'
    Http\Message\ResponseFactory: '@guzzle.psr7.httplug_factory'
    Http\Message\StreamFactory: '@guzzle.psr7.httplug_factory'
    Http\Message\UriFactory: '@guzzle.psr7.httplug_factory'

    guzzle.psr7.psr17_factory:
        class: GuzzleHttp\Psr7\HttpFactory

    guzzle.psr7.httplug_factory:
        class: GuzzleHttp\Psr7\HttpFactory
