apiVersion: v1
kind: Secret
metadata:
  name: lti-keys
type: Opaque
data:
  ltiToolPrivateKey: "{{ .Values.ltiToolPrivateKey | b64enc }}"
  ltiToolPublicKey: "{{ .Values.ltiToolPublicKey | b64enc }}"
