apiVersion: v1
kind: Service
metadata:
  name: {{ include "php.fullname" . }}
  labels: {{- include "php.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: php-fpm
      protocol: TCP
      name: php-fpm
  selector: {{- include "php.selectorLabels" . | nindent 4 }}
