services:
  admin.administrator:
    class: App\Admin\AdministratorAdmin
    tags:
      - name: sonata.admin
        model_class: App\Entity\Administrator
        manager_type: orm
        group: Utilisateurs
        label: Administrateurs
    calls:
      - [setUserManager, ['@App\Service\UserManager']]
    public: true
  
  admin.student:
      class: App\Admin\StudentAdmin
      tags:
          - name: sonata.admin
            model_class: App\Entity\Student
            controller: App\Controller\Admin\StudentAdminController
            manager_type: orm
            group: Utilisateurs
            label: Etudiants

  admin.campus:
      class: App\Admin\CampusAdmin
      tags:
          - name: sonata.admin
            model_class: App\Entity\Campus
            manager_type: orm
            group: Lieux
            label: Campus

  admin.building:
      class: App\Admin\BuildingAdmin
      tags:
          - name: sonata.admin
            model_class: App\Entity\Building
            manager_type: orm
            group: Lieux
            label: Bâtiments

  admin.academic_level:
      class: App\Admin\AcademicLevelAdmin
      tags:
          - name: sonata.admin
            model_class: App\Entity\AcademicLevel
            manager_type: orm
            group: Gestion des tutorats
            label: Niveaux scolaires

  admin.tutoring:
      class: App\Admin\TutoringAdmin
      tags:
          - name: sonata.admin
            model_class: App\Entity\Tutoring
            manager_type: orm
            group: Gestion des tutorats
            label: Tutorats
  
  admin.platform:
      class: App\Admin\Lti\PlatformAdmin
      tags:
          - name: sonata.admin
            model_class: App\Entity\Lti\Platform
            manager_type: orm
            group: Intégration Moodle LTI
            label: Plateformes
  
  admin.registration:
      class: App\Admin\Lti\RegistrationAdmin
      tags:
          - name: sonata.admin
            model_class: App\Entity\Lti\Registration
            manager_type: orm
            group: Intégration Moodle LTI
            label: Intégration
